name: dualprint # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: 'QT-1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A tool to help you save paper when using old priners. # 79 char long summary
description: |
  In order to save paper, one can print multiple pages per sheet, print on
  both sides of a sheet, or do both. Old printers don't usually support
  these printing methods, or do a bad job at combining them. Nevertheless,
  you can acomplish this manually on these printers using a bit of math, or
  using dualPrint.

  dualPrint generates two sets of pages that you copy into the printer
  dialog. Each set corresponds to one side of the document. Follow
  dualPrint's instructions to print on the same sheets twice and your
  document is good to go.
license: MIT

type: app
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
# grade: devel # must be 'stable' to release into candidate/stable channels
# confinement: devmode # use 'strict' once you have the right plugs and slots
icon: ./dualprint.png

parts:
  dualprint:
    plugin: qmake
    qt-version: qt5
    source: "./dualPrint QT 1.0/"
    source-type: local
    project-files: ["dualPrint.pro"]
    override-build: |
      snapcraftctl build
      install -D dualprint $SNAPCRAFT_PART_INSTALL/opt/dualprint/dualprint
    after:
      - desktop-qt5

  # Remote part for support of various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt

    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - try: [appmenu-qt5] # not available on core18
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5

apps:
  dualprint:
    command: desktop-launch $SNAP/opt/dualprint/dualprint
    plugs:
      - desktop
